# ==============================================================================
# core/training_handler.py — Facade Re-export for Training Sub-package
# Sigma Studio v7 — Modular Architecture
# ==============================================================================
"""Facade module for backward compatibility.

All training logic has been decomposed into the modular `core/training/` package:
- core/training/datasets.py  (Dataset Management & HF Search)
- core/training/hardware.py  (CUDA Hardware & VRAM Telemetry)
- core/training/jobs.py      (Training Job Lifecycle & Ollama Export)
"""

import sys
import time
import uuid
import shutil
import subprocess
from urllib.request import urlopen, Request
from urllib.parse import quote, urlencode
from urllib.error import URLError

from core.training.datasets import (
    BASE_DIR,
    TRAINING_DIR,
    DATASETS_DIR,
    FEATURED_DATASETS,
    get_featured_datasets,
    search_hf_datasets,
    get_hf_dataset_info,
    import_local_dataset,
    register_hf_dataset,
    list_imported_datasets,
    list_datasets,
    delete_dataset,
)
from core.training.hardware import (
    _check_torch_cuda,
    _query_nvidia_smi,
    _query_rocm_smi,
    _query_wmi_gpus,
    get_hardware_status,
    get_hardware_info,
    get_gpu_capabilities,
    get_autotune,
    restart_ollama_service,
)
from core.training.fwe import (
    FWE_TARGETS,
    FWE_DATASETS,
    fwe_available,
    fwe_defaults,
    fwe_status,
    list_fwe_runs,
    run_engine_selftest,
)
from core.training.forge import (
    ARCHITECTURES,
    TRAINING_MODES,
    TEACHER_MODELS,
    FEATURED_IT_DATASETS,
    FEATURED_IT_INSTRUCT,
    EXPORT_FORMATS,
    search_italian_datasets,
    dataset_configs,
    forge_defaults,
    forge_status,
    estimate_run,
    dataset_exists,
    search_teacher_models,
    model_accessible,
)
from core.training.checkpoint_chat import (
    list_checkpoints,
    chat as checkpoint_chat,
    unload as unload_checkpoint,
)
from core.training.jobs import (
    JOBS_DIR,
    SCRIPTS_DIR,
    JOBS_FILE,
    SCRIPT_TEMPLATES,
    METHOD_LABELS,
    resolve_dataset,
    reconcile_jobs,
    gpu_process_inventory,
    terminate_gpu_process,
    check_training_dependencies,
    _load_jobs,
    _save_jobs,
    list_training_jobs,
    list_jobs,
    get_job_status,
    create_training_job,
    start_training_job,
    continue_training_job,
    merge_job_adapter,
    get_job_lineage,
    CONTINUATION_MODES,
    stop_training_job,
    pause_training_job,
    resume_training_job,
    update_job_hyperparams,
    delete_job,
    get_job_logs,
    get_job_metrics,
    clear_job_logs,
    export_to_ollama,
    OLLAMA_QUANT_LEVELS,
)

__all__ = [
    "sys",
    "time",
    "uuid",
    "shutil",
    "subprocess",
    "urlopen",
    "Request",
    "quote",
    "urlencode",
    "URLError",
    "BASE_DIR",
    "TRAINING_DIR",
    "DATASETS_DIR",
    "JOBS_DIR",
    "SCRIPTS_DIR",
    "JOBS_FILE",
    "FEATURED_DATASETS",
    "SCRIPT_TEMPLATES",
    "METHOD_LABELS",
    "FWE_TARGETS",
    "FWE_DATASETS",
    "fwe_available",
    "fwe_defaults",
    "fwe_status",
    "list_fwe_runs",
    "run_engine_selftest",
    "resolve_dataset",
    "ARCHITECTURES",
    "TRAINING_MODES",
    "TEACHER_MODELS",
    "FEATURED_IT_DATASETS",
    "FEATURED_IT_INSTRUCT",
    "EXPORT_FORMATS",
    "search_italian_datasets",
    "dataset_configs",
    "forge_defaults",
    "forge_status",
    "estimate_run",
    "dataset_exists",
    "search_teacher_models",
    "model_accessible",
    "list_checkpoints",
    "checkpoint_chat",
    "unload_checkpoint",
    "materialize_fwe_model",
    "reconcile_jobs",
    "gpu_process_inventory",
    "terminate_gpu_process",
    "check_training_dependencies",
    "_load_jobs",
    "_save_jobs",
    "_check_torch_cuda",
    "_query_nvidia_smi",
    "_query_rocm_smi",
    "_query_wmi_gpus",
    "get_featured_datasets",
    "search_hf_datasets",
    "get_hf_dataset_info",
    "import_local_dataset",
    "register_hf_dataset",
    "list_imported_datasets",
    "list_datasets",
    "delete_dataset",
    "get_hardware_status",
    "get_hardware_info",
    "get_gpu_capabilities",
    "get_autotune",
    "restart_ollama_service",
    "list_training_jobs",
    "list_jobs",
    "get_job_status",
    "create_training_job",
    "start_training_job",
    "continue_training_job",
    "merge_job_adapter",
    "get_job_lineage",
    "CONTINUATION_MODES",
    "stop_training_job",
    "pause_training_job",
    "resume_training_job",
    "update_job_hyperparams",
    "delete_job",
    "get_job_logs",
    "get_job_metrics",
    "clear_job_logs",
    "export_to_ollama",
    "OLLAMA_QUANT_LEVELS",
]